name: build
on:
  workflow_run:
    workflows: [ci]
    types: ["completed"]
    branches: ["main"]
jobs:
  ci_:
    runs-on: ubuntu-latest
    needs:
      - ci_web
      - ci_server
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo "hello!!!"
      - name: notify slack
