name: ci
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  ci:
    runs-on: ubuntu-latest
    needs:
      - ci_web
      - ci_server
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: echo "hello!!!"
      - name: notify slack
